project:
  type: website
  resources:
    - readings/dawid-clark-statement.pdf
    - readings/westreich-iliinsky-2014-aje.pdf
    - readings/diaconis-holmes-montgomery-2007-siamreview.pdf
    - readings/matthews-2025-significance.pdf
    - readings/meng-2023-nejsds.pdf
    - readings/detsky-gutekunst-kopac-2025-significance.pdf
    - lecture-notes/sta240-notes-00-set-theory.pdf
    - lecture-notes/sta240-notes-01-probability-spaces.pdf
    - lecture-notes/sta240-notes-02-counting-theory.pdf
    - lecture-notes/sta240-notes-03-counting-examples.pdf
    - lecture-notes/sta240-notes-04-conditional-probability.pdf
    - lecture-notes/sta240-notes-05-random-variables.pdf
    - lecture-notes/sta240-notes-06-discrete-families.pdf
    - lecture-notes/sta240-notes-07-expectation.pdf
    - lecture-notes/sta240-notes-08-variance.pdf
    - lecture-notes/sta240-notes-09-cdf.pdf
    - lecture-notes/sta240-notes-10-absolutely-continuous.pdf
    - lecture-notes/sta240-notes-11-moments.pdf

website:
  page-navigation: true
  title: "STA 240 Fall 2025"
  description: "Homepage for STA 240 Probability for Statistical Inference, Modeling, and Data Analysis at Duke University, Fall 2025."
  site-url: "https://sta240-f25.github.io/"

  open-graph: true

  #draft-mode: unlinked

  sidebar:
    background: "#FFFB71"
    logo: "img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: megaphone
        href: https://go.canvas.duke.edu/
        text: "Canvas"
      - icon: people
        href: https://edstem.org/us/courses/80868/discussion
        text: "Ed Discussion"
      - icon: file-arrow-up
        href: https://www.gradescope.com/courses/1071176
        text: "Gradescope"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Syllabus"
        contents:
          - href: syllabus/syllabus_overview.qmd
            text: Overview
          - href: syllabus/syllabus_team.qmd
            text: Teaching team
          - href: syllabus/syllabus_materials.qmd
            text: Materials
          - href: syllabus/syllabus_assignments.qmd
            text: Assignments and grading
          - href: syllabus/syllabus_policies.qmd
            text: Policies
          - href: syllabus/syllabus_resources.qmd
            text: University resources
          - href: index.qmd
            text: Schedule
      - section: "Math Helpers"
        contents:
          - href: math/greeks.qmd
            text: Greek alphabet
          - href: math/logexp.qmd
            text: Exponents and logarithms
          - href: math/differentiation.qmd
            text: Differentiation
          - href: math/integration.qmd
            text: Integration
          - href: math/limits.qmd
            text: Limits and continuity
          - href: math/series.qmd
            text: Infinite series
          - href: math/gamma-function.qmd
            text: Gamma function
          - href: math/massage-and-squint.qmd
            text: Massage and squint
      - section: "`R` Helpers"
        contents:
          - href: explainers/setup.qmd
            text: Getting started
          - href: explainers/hello-rstudio.qmd
            text: The lay of the land
          - href: explainers/quarto.qmd
            text: Quarto
          - href: explainers/latex.qmd
            text: Typing math
          - href: explainers/math.qmd
            text: Basic math
          - href: explainers/vectors.qmd
            text: Vectors
          - href: explainers/lineplot.qmd
            text: Plotting lines
          - href: explainers/sample.qmd
            text: "`sample`"
          - href: explainers/if-else.qmd
            text: if-else and logic
          - href: explainers/loops.qmd
            text: for loops
          - href: explainers/vectorization.qmd
            text: Vectorization
          - href: explainers/rng-seed.qmd
            text: Setting a seed
          - href: explainers/probabilities.qmd
            text: Computing probabilities
          - href: explainers/plot.qmd
            text: Plotting points
          - href: explainers/summary-statistics.qmd
            text: Summary statistics
          - href: explainers/histogram.qmd
            text: Histograms
      - section: "Distribution Families"
        contents:
          - href: distributions/discrete-binomial.qmd
            text: Binomial
          - href: distributions/discrete-geometric.qmd
            text: Geometric
          - href: distributions/discrete-hypergeometric.qmd
            text: Hypergeometric
          - href: distributions/discrete-poisson.qmd
            text: Poisson
          - href: distributions/continuous-uniform.qmd
            text: Continuous uniform
          - href: distributions/continuous-normal.qmd
            text: Normal
          - href: distributions/continuous-gamma.qmd
            text: Gamma
      - section: "Problem Sets"
        contents:
          - href: problems/pset-0.qmd
            text: Problem Set 0
          - href: problems/pset-1.qmd
            text: Problem Set 1
          - href: problems/pset-2.qmd
            text: Problem Set 2
          - href: problems/pset-3.qmd
            text: Problem Set 3
          - href: problems/pset-4.qmd
            text: Problem Set 4
          - href: problems/pset-5.qmd
            text: Problem Set 5
          - href: problems/pset-6.qmd
            text: Problem Set 6
      - section: "Labs"
        contents:
          - href: labs/lab-1.qmd
            text: Lab 1
          - href: labs/lab-2.qmd
            text: Lab 2
          - href: labs/lab-3.qmd
            text: Lab 3
          - href: labs/lab-4.qmd
            text: Lab 4
          - href: labs/lab-5.qmd
            text: Lab 5
          - href: labs/lab-6.qmd
            text: Lab 6
          - href: labs/lab-7.qmd
            text: Lab 7
      - section: "Exam Study Guides"
        contents:
          - href: problems/exam-midterm-1.qmd
            text: Midterm 1
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025 John Zito"
    background: "#FFFB71"

format: 
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
#  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#798b93"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto