Not all election challenges are frivolous and cynical. Sometimes there are illegal/ineligible ballots in a close election, and if a candidate raises a legal challenge, a court must make a decision: certify the original results? adjust the vote totals somehow, possibly reversing the election? void the results entirely and order a new election? The concern of course is that the presence of the bad ballots might have swung the outcome, but how likely is this? Let's model it.

Imagine an election where Aloysius receives $a$ votes, Bernadette receives $b$ votes, and Aloysius provisionally wins with a margin of victory $a-b>0$. However, of the total $a+b$ votes, we learn that $k>a-b$ were invalid or illegal. But we know nothing else. We do not know who these folks are, where they came from, or who they voted for. We just know that they exist. If the $k$ invalid ballots were removed from the total, what is the probability that it would flip the result of the election? If this probability is "too big," we might start to worry.

To model this, think of the original $a+b$ ballots as balls in the proverbial urn. $a$ of these balls are red, and $b$ of these balls are blue, and assume that $a,\, b>k$. Removing the $k$ invalid ballots is like drawing $k$ balls out of the urn without replacement. Since we know nothing about the illegal ballots apart from the fact that they exist, assume that each of the $a+b$ original ballots is *equally likely* to have been invalid. Next, imagine we randomly remove $k$ balls from the urn, and let $X$ be a random variable that counts the number of the removed/invalid ballots that belong to Aloysius. In other words, the number of red balls removed. If $X$ is large enough, it will swing the election in Bernadette's favor.

a.  What are the range and the pmf of the random variable $X$?
b.  For what values of $X$ does removing $k$ ballots reverse the outcome of the election?
c.  Based on your answers to parts a and b, what is the probability that the election result is reversed when the $k$ bad ballots are removed?
d.  Let's say that we consider the probability of reversal "too big" if it is greater than 5%. Create a figure in `R` that has the margin of victory $a-b$ on the horizontal axis and the number of bad ballots $k$ on the vertical axis. In this figure, draw a line that splits the plane into two parts: the part where the reversal probability is greater than 5% and the part where it is less than 5%;
e.  @tbl-elections features real data on some contested American elections. Add a scatterplot to your previous picture where each point represents an election, and comment on the match or lack thereof between our model and the decision that was actually made;
f.  How do you think a court should handle a legitimate election challenge? What are their responsibilities to the electorate, and what should they prioritize? Should they err on the side of upholding or voiding results? Should they think probabilistically? Should they consult this model, or one like it?

| election | year | win | loss | total | margin | invalid | decision |
|---------|---------|---------|---------|---------|---------|---------|---------|
| *Ippolito v. Power* | 1968 | 1,422 | 1,405 | 2,287 | 17 | 101 | void |
| *Santucci v. Power* | 1969 | 58,076 | 57,981 | 116,057 | 95 | 448 | void |
| *DeMartini v. Power* | 1970 | 2,656 | 2,594 | 5,250 | 62 | 136 | upheld |
| Maine House | 1976 | 1,193 | 1,060 | 2,253 | 133 | 208 | void |
| Ann Arbor mayor | 1977 | 10,660 | 10,659 | 21,319 | 1 | 20 | void |
| Brunswick ME town council | 1980 | 2,390 | 2,383 | 4,773 | 7 | 16 | upheld |
| Washington governor | 2004 | 1,373,357 | 1,373,228 | 2,746,585 | 129 | 1,439 | upheld |

: Close elections {#tbl-elections}

```{r}
#| echo: false
# https://www.nyulawreview.org/wp-content/uploads/2018/08/NYULawReview-83-1-Hickey.pdf
# https://doi.org/10.1198/jasa.2009.ap08640
```
