---
title: "Midterm 1 Study Guide"
format: html
editor: 
  mode: source
draft: false
---

Midterm Exam 1 will take place on **Thursday October 9** during your lab section. There will be 7 problems, and they will break down as follows:

0. (an undisclosed check on your visual intuition)
1. rules
1. counting
1. counting
1. conditional probability
1. conditional probability
1. discrete random variables

Below are new practice problems for each of these areas, as well as guidance about what course materials to refer to if you want more review on a particular topic.

::: callout-important
## Give your cheat sheet some TLC!

You are allowed two resources on the exam:

- a "dumb" calculator (no wi-fi). You will not need it, but if you want it as a security blanket, be my guest;
- both sides of one 8.5" x 11" sheet of notes, prepared by you and you alone. You can create it however you wish: handwritten, on a computer, etc.

Do not skimp on the cheat sheet! Students in past semesters have neglected their cheat sheets to their detriment. Get an early start, and give it some elbow grease.

:::

# Probability spaces

## Problem 1

{{< include bank/basic-rules/geniuses-and-chocolate-lovers.qmd >}}

## Problem 2

{{< include bank/basic-rules/basic-mutually-exclusive-practice.qmd >}}

## Problem 3

{{< include bank/basic-rules/set-minus.qmd >}}

## Problem 4

{{< include bank/basic-rules/xor-2.qmd >}}

## Want more review?

- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-01-probability-spaces.pdf) on axioms and rules;
- [Problem Set 1](https://sta240-f25.github.io/problems/pset-1.html): problems 4 - 8;
- [Problem Set 2](https://sta240-f25.github.io/problems/pset-2.html): problems 2 - 3;

# Counting

## Problem 5

{{< include bank/counting/mak-cards.qmd >}}

## Problem 6

{{< include bank/counting/library-card-PIN.qmd >}}

## Problem 7

{{< include bank/counting/senate-committees.qmd >}}

## Want more review?

- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-02-counting-theory.pdf) on counting theory;
- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-03-counting-examples.pdf) with birthday problem and other worked examples;
- [Lab 2](https://sta240-f25.github.io/labs/lab-2.html) worked examples;
- [Problem Set 1](https://sta240-f25.github.io/problems/pset-1.html): problems 9 - 10;
- [Problem Set 2](https://sta240-f25.github.io/problems/pset-2.html): problems 4 - 8;
- [Problem Set 3](https://sta240-f25.github.io/problems/pset-3.html): problems 2 - 3;
- Odd-numbered exercises in DeGroot & Schervish Chapters 1.6 - 1.8, 1.12.

# Conditional probability 

## Problem 8

{{< include bank/conditional-probability/face-cards.qmd >}}

## Problem 9

{{< include bank/conditional-probability/all-white-balls.qmd >}}

## Problem 10

{{< include bank/conditional-probability/pairwise-versus-mutual-independence.qmd >}}

## Want more review?

- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-04-conditional-probability.pdf) with worked examples;
    - The lil' [app](https://sta240-f25.github.io/apps/disease-testing.html) on disease testing;
- [Problem Set 2](https://sta240-f25.github.io/problems/pset-2.html): problems 9 - 10;
- [Problem Set 3](https://sta240-f25.github.io/problems/pset-3.html): problems 4 - 8;
- [Problem Set 4](https://sta240-f25.github.io/problems/pset-4.html): problems 2 - 3;
- Odd-numbered exercises in DeGroot & Schervish Chapter 2.

# Discrete random variables

## Problem 11

{{< include bank/random-variables-discrete/fibonacci-dice.qmd >}}

## Problem 12

{{< include bank/random-variables-discrete/memoryless-geometric.qmd >}}

## Want more review?

- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-05-random-variables.pdf) introducing random variables;
- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-06-discrete-families.pdf) on special families of discrete random variables;
- [Lecture notes](https://sta240-f25.github.io/lecture-notes/sta240-notes-07-expectation.pdf) on expected value;
- [Lab 5](https://sta240-f25.github.io/labs/lab-5.html) exercises;
- [Problem Set 2](https://sta240-f25.github.io/problems/pset-2.html): problem 7;
- [Problem Set 3](https://sta240-f25.github.io/problems/pset-3.html): problems 9 - 10;
- [Problem Set 4](https://sta240-f25.github.io/problems/pset-4.html): problems 4 - 10.

